### ISSUE TITLE
Servidor Tracker

### ISSUE THREAD

**Issue by tm-sm** [mquesada02/TPE-PROTOS#3]
Requisitos:

- [x] Almacenar una lista de usuario:contraseña (no volátil)
- [x] Almacenar una lista de archivos con los usuarios que lo comparten (volátil)
- [x] Almacenar una lista de usuarios con los ip:puertos que tienen disponibles (volátil)
- [x] Eliminar cualquier usuario que no envíe su ip:puertos + archivos compartidos después de x cantidad de tiempo (solo en los datos volátiles)
